### ISSUE TITLE
How can i use graphserviceclient in wasm blazor client 

### ISSUE THREAD

**Issue by rubeesh** [wmgdev/BlazorGraphApi#3]
How can i use graphserviceclient in wasm blazor client.

**Comment by wmgdev** [comment]
> How can i use graphserviceclient in wasm blazor client.

Sorry this demo app is focused on Blazor Server, you will need to take a different approach if using wasm
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-3.1
