### ISSUE TITLE
Retrieve token on page load

### ISSUE THREAD

**Issue by thaihoangcfc** [wmgdev/BlazorGraphApi#5]
Hi,

Thank you so much for the Graph solution on Blazor. Just one question, when I implement your profile page (profile.razor) on my project, everytime I navigate to it, the page redirects to a 'login.microsoftonline.com/common/...' URL, I suppose it was trying to request the token for a Graph call, then go back to the profile page with sufficient information of singed-in user. This is no big problem but a bit of hassle, as I expected the token to be retrieved straight away after signing in as an Office 365 user, and I just can call Graph at any places in my Blazor App without being redirected to MS Auth.
Can this step (retrieving token and have Graph ready) be done right at home page (index.razor) rendering? For example, inside OnInitializedAsync? I tried to put the profile API call into Index but I received an exception with ConsentHandler in the exception handling block.

Thank you!

**Comment by wmgdev** [comment]
Yes seems strange
Not sure why we are getting a problem when moving the graph api call and ConsentHandler into index.razor - OnInitializedAsync
I'll look into it, we may have to raise an issue on Microsoft.Identity.Web project

**Comment by wmgdev** [comment]
You should only get the redirect to login.microsoft, when the token does not already exist in the InMemoryTokenCache, if there is no entry in the cache we have to authenticate the user, this handled in the exception by the ConsentHandler.
The in memory token cache will get dropped every time you restart the server.

There is a bug in Microsoft.Indentity.Web which stops the ConsentHandler working properly in index.razor
See this issue https://github.com/AzureAD/microsoft-identity-web/issues/437

The workaround is to turn off serverprerendering in _Host.cshtml


```
<app>
        <component type="typeof(App)" render-mode="Server" />
</app>
```

It looks like they have fixed it, hopefully it will be in the next release, they are pretty good at getting the releases out quick, I will update when they do

**Comment by thaihoangcfc** [comment]
Yes I have just changed the render mode and it seems better now. Considering the Identity library is still in preview stage, hope they can make this stable and offer a better solution for Blazor.

Thank you for your help :)

**Comment by jennyf19** [comment]
@wmgdev @thaihoangcfc yes, the changes for blazor will be in the next Microsoft Identity Web release, sometime this week (week of Aug. 17). If you run into issues w/Microsoft Identity Web + blazor, please open an issue so we can investigate. Appreciate the responsiveness from the community in finding issues. If you're calling MS Graph, you might want to have this [issue](https://github.com/AzureAD/microsoft-identity-web/issues/438) on your radar as well.

**Comment by jennyf19** [comment]
Also, to handle incremental consent, you need to make a few adjustments as well...see the [wiki](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-blazor-server) for more information.
