### ISSUE TITLE
Trying to convert this sample to multi tenant

### ISSUE THREAD

**Issue by EdAlexander** [wmgdev/BlazorGraphApi#6]
Does anyone have any ideas regarding updsating this sample to multi-tenant?  Simply marking the app registration multi tenant is not enough.  Thoughts?  My ultimate goal is to add graph access and functionaility to an existing Blazor server application (multi-tenant AzureAD Auth).

**Comment by wmgdev** [comment]
Ask on the Microsoft.Identity.Web repo
https://github.com/AzureAD/microsoft-identity-web
They are Blazor aware

**Comment by EdAlexander** [comment]
Thanks for the suggestion... posting issue there...
