### ISSUE TITLE
Scope - Refresh Token

### ISSUE THREAD

**Issue by Doverso** [wmgdev/BlazorGraphApi#7]
Under app.settings, if "CalledApiScopes": "user.read offline_access" - is updated to include 'offline_access' how does a refresh token get acquired? Would this be true in this example? Does offline_access/refresh token work with Microsoft.Indentity.Web?

**Comment by wmgdev** [comment]
I think scope **offline_access** is always requested by default by Msal (and therefore Microsoft.Identity.Web), it handles all access and refresh tokens and puts them in the token cache
