### ISSUE TITLE
Azure Signalr Service

### ISSUE THREAD

**Issue by jassent** [wmgdev/BlazorGraphApi#9]
First, thank you so much for the solid example.

When I add Azure Signalr Service to the project the /profile page constantly refreshes  With each refresh it is calling the login.microsoftonline.com service. The profile information actually loads and displays on the page. Debug shows the following error on each refresh which isn't particularly helpful:

`Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
System.Net.Http.HttpClient.Default.LogicalHandler: Information: Start processing HTTP request POST https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/token
System.Net.Http.HttpClient.Default.ClientHandler: Information: Sending HTTP request POST https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/token
System.Net.Http.HttpClient.Default.ClientHandler: Information: Received HTTP response after 201.8975ms - OK
System.Net.Http.HttpClient.Default.LogicalHandler: Information: End processing HTTP request after 209.1404ms - OK`

Any ideas? The same exact code works fine when using locally hosted SignalR.

**Comment by jassent** [comment]
If it helps...Here is a repository that shows the bug: https://github.com/jtawil777/BlazorGraphApiAzureSignalrServiceExample

I also filed a bug with Microsoft.Identity.Web: https://github.com/AzureAD/microsoft-identity-web/issues/573

**Comment by wmgdev** [comment]
Regards. Looks like they can reproduce, so fingers crossed.
This example project has evolved over time. Now that Microsoft.Identity.Web has improved and embraced Blazor Server, it's now pretty much a copy of the "blazorserver --auth SingleOrg --calls-graph" example app in their Repro

**Comment by jassent** [comment]
Agreed! Thank you for helping me get started down this road.
